// 由 scripts/fetch-season.mjs 自动生成 — 2026 summer 档候选
// ⚠️ 人工复核后合并进 songs.js：titleCN 建议用 Bangumi 中文名核对，确认后 bump 版本号
export const CANDIDATES = [
  {
    "title": "Inori, Owareba",
    "titleCN": "Inori, Owareba",
    "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
    "animeCN": "无职转生Ⅲ ～异世界认真活下去～",
    "artist": "Mika Nakashima",
    "type": "ED",
    "popularity": 151620,
    "averageScore": 84,
    "anilistId": 178789,
    "slug": "mushoku_tensei_iii_isekai_ittara_honki_dasu",
    "animethemeUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu"
  },
  {
    "title": "Ketsui no Uta",
    "titleCN": "Ketsui no Uta",
    "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
    "animeCN": "无职转生Ⅲ ～异世界认真活下去～",
    "artist": "Yuiko Oohara",
    "type": "OP",
    "popularity": 151620,
    "averageScore": 84,
    "anilistId": 178789,
    "slug": "mushoku_tensei_iii_isekai_ittara_honki_dasu",
    "animethemeUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu"
  },
  {
    "title": "Fiction",
    "titleCN": "Fiction",
    "anime": "Super no Ura de Yani Suu Futari",
    "animeCN": "在超市后门吸烟的二人",
    "artist": "imase",
    "type": "ED",
    "popularity": 115213,
    "averageScore": 82,
    "anilistId": 196187,
    "slug": "super_no_ura_de_yani_suu_futari",
    "animethemeUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari"
  },
  {
    "title": "Ichijiku Kemuri",
    "titleCN": "Ichijiku Kemuri",
    "anime": "Super no Ura de Yani Suu Futari",
    "animeCN": "在超市后门吸烟的二人",
    "artist": "Zutto Mayonaka de Ii no ni.",
    "type": "OP",
    "popularity": 115213,
    "averageScore": 82,
    "anilistId": 196187,
    "slug": "super_no_ura_de_yani_suu_futari",
    "animethemeUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari"
  },
  {
    "title": "Weiter! Weiter!",
    "titleCN": "Weiter! Weiter!",
    "anime": "Youjo Senki II",
    "animeCN": "幼女战记Ⅱ",
    "artist": "Aoi Yuuki",
    "type": "ED",
    "popularity": 90759,
    "averageScore": 80,
    "anilistId": 135865,
    "slug": "youjo_senki_ii",
    "animethemeUrl": "https://animethemes.moe/anime/youjo_senki_ii"
  },
  {
    "title": "Why? RED induction",
    "titleCN": "Why? RED induction",
    "anime": "Youjo Senki II",
    "animeCN": "幼女战记Ⅱ",
    "artist": "MYTH & ROID",
    "type": "OP",
    "popularity": 90759,
    "averageScore": 80,
    "anilistId": 135865,
    "slug": "youjo_senki_ii",
    "animethemeUrl": "https://animethemes.moe/anime/youjo_senki_ii"
  },
  {
    "title": "Rasen",
    "titleCN": "Rasen",
    "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
    "animeCN": "死神 千年血战篇-相克谭-",
    "artist": "9Lana",
    "type": "ED",
    "popularity": 82571,
    "averageScore": 90,
    "anilistId": 185874,
    "slug": "bleach_sennen_kessenhen_kashintan",
    "animethemeUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan"
  },
  {
    "title": "I-BULL",
    "titleCN": "I-BULL",
    "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
    "animeCN": "死神 千年血战篇-相克谭-",
    "artist": "jo0ji",
    "type": "OP",
    "popularity": 82571,
    "averageScore": 90,
    "anilistId": 185874,
    "slug": "bleach_sennen_kessenhen_kashintan",
    "animethemeUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan"
  },
  {
    "title": "Kemuri to Blue",
    "titleCN": "Kemuri to Blue",
    "anime": "Yani Neko",
    "animeCN": "夜猫",
    "artist": "Necry Talkie",
    "type": "ED",
    "popularity": 70498,
    "averageScore": 67,
    "anilistId": 207141,
    "slug": "yani_neko",
    "animethemeUrl": "https://animethemes.moe/anime/yani_neko"
  },
  {
    "title": "Nanmonee",
    "titleCN": "Nanmonee",
    "anime": "Yani Neko",
    "animeCN": "夜猫",
    "artist": "Wasureranneyo",
    "type": "OP",
    "popularity": 70498,
    "averageScore": 67,
    "anilistId": 207141,
    "slug": "yani_neko",
    "animethemeUrl": "https://animethemes.moe/anime/yani_neko"
  },
  {
    "title": "Groooovy",
    "titleCN": "Groooovy",
    "anime": "BLACK TORCH",
    "animeCN": "黑之火炬",
    "artist": "I Don't Like Mondays.",
    "type": "ED",
    "popularity": 65187,
    "averageScore": 70,
    "anilistId": 187538,
    "slug": "black_torch",
    "animethemeUrl": "https://animethemes.moe/anime/black_torch"
  },
  {
    "title": "FREEZE ME UP",
    "titleCN": "FREEZE ME UP",
    "anime": "BLACK TORCH",
    "animeCN": "黑之火炬",
    "artist": "SiM",
    "type": "OP",
    "popularity": 65187,
    "averageScore": 70,
    "anilistId": 187538,
    "slug": "black_torch",
    "animethemeUrl": "https://animethemes.moe/anime/black_torch"
  },
  {
    "title": "Lv.1 Shokugyou:Ningen",
    "titleCN": "Lv.1 Shokugyou:Ningen",
    "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
    "animeCN": "被放逐的转生重骑士靠游戏知识无双",
    "artist": "ReoNa",
    "type": "ED",
    "popularity": 58925,
    "averageScore": 66,
    "anilistId": 180136,
    "slug": "tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
    "animethemeUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru"
  },
  {
    "title": "Awake",
    "titleCN": "Awake",
    "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
    "animeCN": "被放逐的转生重骑士靠游戏知识无双",
    "artist": "SPYAIR",
    "type": "OP",
    "popularity": 58925,
    "averageScore": 66,
    "anilistId": 180136,
    "slug": "tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
    "animethemeUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru"
  },
  {
    "title": "Unmei no Kimi",
    "titleCN": "Unmei no Kimi",
    "anime": "Seihantai na Kimi to Boku 2nd Season",
    "animeCN": "反方向的你和我 第二季",
    "artist": "Mega Shinnosuke",
    "type": "ED",
    "popularity": 57033,
    "averageScore": 82,
    "anilistId": 210031,
    "slug": "seihantai_na_kimi_to_boku_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season"
  },
  {
    "title": "Nekojarashi",
    "titleCN": "Nekojarashi",
    "anime": "Seihantai na Kimi to Boku 2nd Season",
    "animeCN": "反方向的你和我 第二季",
    "artist": "7co",
    "type": "OP",
    "popularity": 57033,
    "averageScore": 82,
    "anilistId": 210031,
    "slug": "seihantai_na_kimi_to_boku_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season"
  },
  {
    "title": "Soarin'",
    "titleCN": "Soarin'",
    "anime": "Nijusseiki Denki Mokuroku: Eureka Evrika",
    "animeCN": "二十世纪电气目录：尤里卡·埃夫里卡",
    "artist": "Ginger Root",
    "type": "ED",
    "popularity": 54581,
    "averageScore": 76,
    "anilistId": 103303,
    "slug": "nijusseiki_denki_mokuroku_eureka_evrika",
    "animethemeUrl": "https://animethemes.moe/anime/nijusseiki_denki_mokuroku_eureka_evrika"
  },
  {
    "title": "Eureka Evrika",
    "titleCN": "Eureka Evrika",
    "anime": "Nijusseiki Denki Mokuroku: Eureka Evrika",
    "animeCN": "二十世纪电气目录：尤里卡·埃夫里卡",
    "artist": "Luna Goami",
    "type": "OP",
    "popularity": 54581,
    "averageScore": 76,
    "anilistId": 103303,
    "slug": "nijusseiki_denki_mokuroku_eureka_evrika",
    "animethemeUrl": "https://animethemes.moe/anime/nijusseiki_denki_mokuroku_eureka_evrika"
  },
  {
    "title": "Eternal",
    "titleCN": "Eternal",
    "anime": "Kimi ga Shinu made Koi wo Shitai",
    "animeCN": "想和你谈一场直到死去的恋爱",
    "artist": "sajou no hana",
    "type": "ED",
    "popularity": 53456,
    "averageScore": 74,
    "anilistId": 187260,
    "slug": "kimi_ga_shinu_made_koi_wo_shitai",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_ga_shinu_made_koi_wo_shitai"
  },
  {
    "title": "Amore",
    "titleCN": "Amore",
    "anime": "Kimi ga Shinu made Koi wo Shitai",
    "animeCN": "想和你谈一场直到死去的恋爱",
    "artist": "ReoNa",
    "type": "OP",
    "popularity": 53456,
    "averageScore": 74,
    "anilistId": 187260,
    "slug": "kimi_ga_shinu_made_koi_wo_shitai",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_ga_shinu_made_koi_wo_shitai"
  },
  {
    "title": "Ashita wa Ashita no Ke Sera Sera!",
    "titleCN": "Ashita wa Ashita no Ke Sera Sera!",
    "anime": "Otomege Sekai wa Mob ni Kibishii Sekai desu 2",
    "animeCN": "乙女游戏世界对路人角色太不友好 第二季",
    "artist": "MEISHOHIKOKAI",
    "type": "ED",
    "popularity": 51530,
    "averageScore": 68,
    "anilistId": 159309,
    "slug": "otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2",
    "animethemeUrl": "https://animethemes.moe/anime/otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2"
  },
  {
    "title": "Jinsei End Roll",
    "titleCN": "Jinsei End Roll",
    "anime": "Otomege Sekai wa Mob ni Kibishii Sekai desu 2",
    "animeCN": "乙女游戏世界对路人角色太不友好 第二季",
    "artist": "Ando",
    "type": "OP",
    "popularity": 51530,
    "averageScore": 68,
    "anilistId": 159309,
    "slug": "otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2",
    "animethemeUrl": "https://animethemes.moe/anime/otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2"
  },
  {
    "title": "Blue",
    "titleCN": "Blue",
    "anime": "Koukaku Kidoutai: THE GHOST IN THE SHELL",
    "animeCN": "攻壳机动队（1995）",
    "artist": "millennium parade",
    "type": "ED",
    "popularity": 51370,
    "averageScore": 76,
    "anilistId": 177699,
    "slug": "koukaku_kidoutai_the_ghost_in_the_shell",
    "animethemeUrl": "https://animethemes.moe/anime/koukaku_kidoutai_the_ghost_in_the_shell"
  },
  {
    "title": "GO GHOST",
    "titleCN": "GO GHOST",
    "anime": "Koukaku Kidoutai: THE GHOST IN THE SHELL",
    "animeCN": "攻壳机动队（1995）",
    "artist": "King Gnu",
    "type": "OP",
    "popularity": 51370,
    "averageScore": 76,
    "anilistId": 177699,
    "slug": "koukaku_kidoutai_the_ghost_in_the_shell",
    "animethemeUrl": "https://animethemes.moe/anime/koukaku_kidoutai_the_ghost_in_the_shell"
  },
  {
    "title": "Kiseki wa Okinai",
    "titleCN": "Kiseki wa Okinai",
    "anime": "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu II",
    "animeCN": "骸骨骑士大人异世界冒险中 第二季",
    "artist": "DIALOGUE+",
    "type": "ED",
    "popularity": 47134,
    "averageScore": 66,
    "anilistId": 185542,
    "slug": "gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii",
    "animethemeUrl": "https://animethemes.moe/anime/gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii"
  },
  {
    "title": "Roman Kaidou, Osanpo-chuu",
    "titleCN": "Roman Kaidou, Osanpo-chuu",
    "anime": "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu II",
    "animeCN": "骸骨骑士大人异世界冒险中 第二季",
    "artist": "PelleK",
    "type": "OP",
    "popularity": 47134,
    "averageScore": 66,
    "anilistId": 185542,
    "slug": "gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii",
    "animethemeUrl": "https://animethemes.moe/anime/gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii"
  },
  {
    "title": "Awake Anew",
    "titleCN": "Awake Anew",
    "anime": "Clevatess II: Majuu no Ou to Itsuwari no Yuusha Denshou",
    "animeCN": "ClevatessⅡ 魔王之王与伪英雄传承",
    "artist": "MYTH & ROID",
    "type": "ED",
    "popularity": 42788,
    "averageScore": 75,
    "anilistId": 198946,
    "slug": "clevatess_ii_majuu_no_ou_to_itsuwari_no_yuusha_denshou",
    "animethemeUrl": "https://animethemes.moe/anime/clevatess_ii_majuu_no_ou_to_itsuwari_no_yuusha_denshou"
  },
  {
    "title": "Foreshadow",
    "titleCN": "Foreshadow",
    "anime": "Clevatess II: Majuu no Ou to Itsuwari no Yuusha Denshou",
    "animeCN": "ClevatessⅡ 魔王之王与伪英雄传承",
    "artist": "Mayu Maeshima",
    "type": "OP",
    "popularity": 42788,
    "averageScore": 75,
    "anilistId": 198946,
    "slug": "clevatess_ii_majuu_no_ou_to_itsuwari_no_yuusha_denshou",
    "animethemeUrl": "https://animethemes.moe/anime/clevatess_ii_majuu_no_ou_to_itsuwari_no_yuusha_denshou"
  },
  {
    "title": "Hikari",
    "titleCN": "Hikari",
    "anime": "Toumei na Yoru ni Kakeru Kimi to, Me ni Mienai Koi wo Shita.",
    "animeCN": "在透明的夜空中奔向你，与看不见的恋爱",
    "artist": "Yui Sakurai",
    "type": "ED",
    "popularity": 42549,
    "averageScore": 79,
    "anilistId": 202269,
    "slug": "toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita",
    "animethemeUrl": "https://animethemes.moe/anime/toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita"
  },
  {
    "title": "Hitohira",
    "titleCN": "Hitohira",
    "anime": "Toumei na Yoru ni Kakeru Kimi to, Me ni Mienai Koi wo Shita.",
    "animeCN": "在透明的夜空中奔向你，与看不见的恋爱",
    "artist": "Motohiro Hata",
    "type": "OP",
    "popularity": 42549,
    "averageScore": 79,
    "anilistId": 202269,
    "slug": "toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita",
    "animethemeUrl": "https://animethemes.moe/anime/toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita"
  },
  {
    "title": "Mikansei",
    "titleCN": "Mikansei",
    "anime": "Katainaka no Ossan, Kensei ni Naru II",
    "animeCN": "乡下大叔成为剑圣 第二季",
    "artist": "BLUE ENCOUNT",
    "type": "ED",
    "popularity": 42378,
    "averageScore": 70,
    "anilistId": 194829,
    "slug": "katainaka_no_ossan_kensei_ni_naru_ii",
    "animethemeUrl": "https://animethemes.moe/anime/katainaka_no_ossan_kensei_ni_naru_ii"
  },
  {
    "title": "Kurenai no Ha",
    "titleCN": "Kurenai no Ha",
    "anime": "Katainaka no Ossan, Kensei ni Naru II",
    "animeCN": "乡下大叔成为剑圣 第二季",
    "artist": "Unicorn",
    "type": "OP",
    "popularity": 42378,
    "averageScore": 70,
    "anilistId": 194829,
    "slug": "katainaka_no_ossan_kensei_ni_naru_ii",
    "animethemeUrl": "https://animethemes.moe/anime/katainaka_no_ossan_kensei_ni_naru_ii"
  },
  {
    "title": "Kanpeki ja Nai Watashi",
    "titleCN": "Kanpeki ja Nai Watashi",
    "anime": "Saijo no Osewa: Takane no Hanadarake na Meimonkou de, Gakuin Ichi no Ojou-sama (Seikatsu Nouryoku Kaimu) wo Kagenagara Osewa suru Koto ni Narimashita",
    "animeCN": "最上大小姐的世话：照顾学院第一大小姐（生活能力为零）",
    "artist": "Ami Maeshima",
    "type": "ED",
    "popularity": 40881,
    "averageScore": 70,
    "anilistId": 201514,
    "slug": "saijo_no_osewa_takane_no_hanadarake_na_meimonkou_de_gakuin_ichi_no_ojousama_seikatsu_nouryoku_kaimu_wo_kagenagara_osewa_suru_koto_ni_narimashita",
    "animethemeUrl": "https://animethemes.moe/anime/saijo_no_osewa_takane_no_hanadarake_na_meimonkou_de_gakuin_ichi_no_ojousama_seikatsu_nouryoku_kaimu_wo_kagenagara_osewa_suru_koto_ni_narimashita"
  },
  {
    "title": "Saisaisaikoukyuu no Osewa Shite",
    "titleCN": "Saisaisaikoukyuu no Osewa Shite",
    "anime": "Saijo no Osewa: Takane no Hanadarake na Meimonkou de, Gakuin Ichi no Ojou-sama (Seikatsu Nouryoku Kaimu) wo Kagenagara Osewa suru Koto ni Narimashita",
    "animeCN": "最上大小姐的世话：照顾学院第一大小姐（生活能力为零）",
    "artist": "angela",
    "type": "OP",
    "popularity": 40881,
    "averageScore": 70,
    "anilistId": 201514,
    "slug": "saijo_no_osewa_takane_no_hanadarake_na_meimonkou_de_gakuin_ichi_no_ojousama_seikatsu_nouryoku_kaimu_wo_kagenagara_osewa_suru_koto_ni_narimashita",
    "animethemeUrl": "https://animethemes.moe/anime/saijo_no_osewa_takane_no_hanadarake_na_meimonkou_de_gakuin_ichi_no_ojousama_seikatsu_nouryoku_kaimu_wo_kagenagara_osewa_suru_koto_ni_narimashita"
  },
  {
    "title": "Hoshi",
    "titleCN": "Hoshi",
    "anime": "Tenmaku no Jaadugar",
    "animeCN": "天幕的魔导师",
    "artist": "Ziyoou-vachi",
    "type": "ED",
    "popularity": 40771,
    "averageScore": 82,
    "anilistId": 190569,
    "slug": "tenmaku_no_jaadugar",
    "animethemeUrl": "https://animethemes.moe/anime/tenmaku_no_jaadugar"
  },
  {
    "title": "Stella",
    "titleCN": "Stella",
    "anime": "Tenmaku no Jaadugar",
    "animeCN": "天幕的魔导师",
    "artist": "SEKAI NO OWARI",
    "type": "OP",
    "popularity": 40771,
    "averageScore": 82,
    "anilistId": 190569,
    "slug": "tenmaku_no_jaadugar",
    "animethemeUrl": "https://animethemes.moe/anime/tenmaku_no_jaadugar"
  },
  {
    "title": "Hadaka no Mermaid",
    "titleCN": "Hadaka no Mermaid",
    "anime": "Grand Blue Season 3",
    "animeCN": "碧蓝之海 第三季",
    "artist": "MAMESHiBA NO TAiGUN",
    "type": "ED",
    "popularity": 39696,
    "averageScore": 82,
    "anilistId": 199111,
    "slug": "grand_blue_season_3",
    "animethemeUrl": "https://animethemes.moe/anime/grand_blue_season_3"
  },
  {
    "title": "Natsuko",
    "titleCN": "Natsuko",
    "anime": "Grand Blue Season 3",
    "animeCN": "碧蓝之海 第三季",
    "artist": "FUNKY MONKEY BΛBY'S",
    "type": "OP",
    "popularity": 39696,
    "averageScore": 82,
    "anilistId": 199111,
    "slug": "grand_blue_season_3",
    "animethemeUrl": "https://animethemes.moe/anime/grand_blue_season_3"
  },
  {
    "title": "Kore Koi Itare Ai",
    "titleCN": "Kore Koi Itare Ai",
    "anime": "Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo 3rd Season",
    "animeCN": "超超超超超喜欢你的100个女朋友 第三季",
    "artist": "Rentarou Family",
    "type": "ED",
    "popularity": 38383,
    "averageScore": 79,
    "anilistId": 200637,
    "slug": "kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100nin_no_kanojo_3rd_season",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100nin_no_kanojo_3rd_season"
  },
  {
    "title": "Daisuki♡Zutto Eien ni♡",
    "titleCN": "Daisuki♡Zutto Eien ni♡",
    "anime": "Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo 3rd Season",
    "animeCN": "超超超超超喜欢你的100个女朋友 第三季",
    "artist": "Rentarou Family",
    "type": "OP",
    "popularity": 38383,
    "averageScore": 79,
    "anilistId": 200637,
    "slug": "kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100nin_no_kanojo_3rd_season",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_no_koto_ga_dai_dai_dai_dai_daisuki_na_100nin_no_kanojo_3rd_season"
  },
  {
    "title": "Tilt",
    "titleCN": "Tilt",
    "anime": "Tenkousaki no Seiso Karen na Bishoujo ga, Mukashi Danshi to Omotte Issho ni Asonda Osananajimi datta Ken",
    "animeCN": "转校的清纯可爱美少女，过去是被当作男生的青梅竹马",
    "artist": "harmoe",
    "type": "ED",
    "popularity": 38281,
    "averageScore": 70,
    "anilistId": 169583,
    "slug": "tenkousaki_no_seiso_karen_na_bishoujo_ga_mukashi_danshi_to_omotte_issho_ni_asonda_osananajimi_datta_ken",
    "animethemeUrl": "https://animethemes.moe/anime/tenkousaki_no_seiso_karen_na_bishoujo_ga_mukashi_danshi_to_omotte_issho_ni_asonda_osananajimi_datta_ken"
  },
  {
    "title": "Natsu ni Kasanete",
    "titleCN": "Natsu ni Kasanete",
    "anime": "Tenkousaki no Seiso Karen na Bishoujo ga, Mukashi Danshi to Omotte Issho ni Asonda Osananajimi datta Ken",
    "animeCN": "转校的清纯可爱美少女，过去是被当作男生的青梅竹马",
    "artist": "DIALOGUE+",
    "type": "OP",
    "popularity": 38281,
    "averageScore": 70,
    "anilistId": 169583,
    "slug": "tenkousaki_no_seiso_karen_na_bishoujo_ga_mukashi_danshi_to_omotte_issho_ni_asonda_osananajimi_datta_ken",
    "animethemeUrl": "https://animethemes.moe/anime/tenkousaki_no_seiso_karen_na_bishoujo_ga_mukashi_danshi_to_omotte_issho_ni_asonda_osananajimi_datta_ken"
  },
  {
    "title": "Houkiboshi",
    "titleCN": "Houkiboshi",
    "anime": "Futsutsuka na Akujo de wa Gozaimasu ga: Suuguu Chouso Torikae Den",
    "animeCN": "我是不争气的恶女：救急朝臣·替身传（待核对）",
    "artist": "Rokudenashi",
    "type": "ED",
    "popularity": 38145,
    "averageScore": 77,
    "anilistId": 188139,
    "slug": "futsutsuka_na_akujo_de_wa_gozaimasu_ga_suuguu_chouso_torikae_den",
    "animethemeUrl": "https://animethemes.moe/anime/futsutsuka_na_akujo_de_wa_gozaimasu_ga_suuguu_chouso_torikae_den"
  },
  {
    "title": "Sunny",
    "titleCN": "Sunny",
    "anime": "Futsutsuka na Akujo de wa Gozaimasu ga: Suuguu Chouso Torikae Den",
    "animeCN": "我是不争气的恶女：救急朝臣·替身传（待核对）",
    "artist": "milet",
    "type": "OP",
    "popularity": 38145,
    "averageScore": 77,
    "anilistId": 188139,
    "slug": "futsutsuka_na_akujo_de_wa_gozaimasu_ga_suuguu_chouso_torikae_den",
    "animethemeUrl": "https://animethemes.moe/anime/futsutsuka_na_akujo_de_wa_gozaimasu_ga_suuguu_chouso_torikae_den"
  },
  {
    "title": "Firetail",
    "titleCN": "Firetail",
    "anime": "Hell Mode: Yarikomi-zuki no Gamer wa Haisettei no Isekai de Musou Suru 2nd Season",
    "animeCN": "地狱模式：肝帝玩家的最强异世界无双 第二季",
    "artist": "ChoQMay",
    "type": "ED",
    "popularity": 37605,
    "averageScore": 72,
    "anilistId": 209983,
    "slug": "hell_mode_yarikomizuki_no_gamer_wa_haisettei_no_isekai_de_musou_suru_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/hell_mode_yarikomizuki_no_gamer_wa_haisettei_no_isekai_de_musou_suru_2nd_season"
  },
  {
    "title": "○✕△□",
    "titleCN": "○✕△□",
    "anime": "Hell Mode: Yarikomi-zuki no Gamer wa Haisettei no Isekai de Musou Suru 2nd Season",
    "animeCN": "地狱模式：肝帝玩家的最强异世界无双 第二季",
    "artist": "Romanha Marshmallow",
    "type": "OP",
    "popularity": 37605,
    "averageScore": 72,
    "anilistId": 209983,
    "slug": "hell_mode_yarikomizuki_no_gamer_wa_haisettei_no_isekai_de_musou_suru_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/hell_mode_yarikomizuki_no_gamer_wa_haisettei_no_isekai_de_musou_suru_2nd_season"
  },
  {
    "title": "Hearts Glow",
    "titleCN": "Hearts Glow",
    "anime": "Sayonara Lara",
    "animeCN": "再见，拉拉",
    "artist": "Hana Hope",
    "type": "ED",
    "popularity": 30879,
    "averageScore": 76,
    "anilistId": 177637,
    "slug": "sayonara_lara",
    "animethemeUrl": "https://animethemes.moe/anime/sayonara_lara"
  },
  {
    "title": "Sayonara Lara",
    "titleCN": "Sayonara Lara",
    "anime": "Sayonara Lara",
    "animeCN": "再见，拉拉",
    "artist": "Ikimonogakari",
    "type": "OP",
    "popularity": 30879,
    "averageScore": 76,
    "anilistId": 177637,
    "slug": "sayonara_lara",
    "animethemeUrl": "https://animethemes.moe/anime/sayonara_lara"
  },
  {
    "title": "NEW GAME",
    "titleCN": "NEW GAME",
    "anime": "Tai-Ari deshita.: Ojou-sama wa Kakutou Game nante Shinai",
    "animeCN": "曾有过对决。：大小姐才不会玩格斗游戏",
    "artist": "halca",
    "type": "ED",
    "popularity": 26973,
    "averageScore": 74,
    "anilistId": 128757,
    "slug": "taiari_deshita_ojousama_wa_kakutou_game_nante_shinai",
    "animethemeUrl": "https://animethemes.moe/anime/taiari_deshita_ojousama_wa_kakutou_game_nante_shinai"
  },
  {
    "title": "Inochi Mijikashi Taisuru Otome yo",
    "titleCN": "Inochi Mijikashi Taisuru Otome yo",
    "anime": "Tai-Ari deshita.: Ojou-sama wa Kakutou Game nante Shinai",
    "animeCN": "曾有过对决。：大小姐才不会玩格斗游戏",
    "artist": "HANABIE.",
    "type": "OP",
    "popularity": 26973,
    "averageScore": 74,
    "anilistId": 128757,
    "slug": "taiari_deshita_ojousama_wa_kakutou_game_nante_shinai",
    "animethemeUrl": "https://animethemes.moe/anime/taiari_deshita_ojousama_wa_kakutou_game_nante_shinai"
  },
  {
    "title": "Owaranai Yoru no Mamorikata",
    "titleCN": "Owaranai Yoru no Mamorikata",
    "anime": "Sekai Saikyou no Kouei: Meikyuukoku no Shinjin Tansakusha",
    "animeCN": "世界最强的后卫：迷宫国的新人探索者",
    "artist": "Inner Journey",
    "type": "ED",
    "popularity": 26830,
    "averageScore": 55,
    "anilistId": 198409,
    "slug": "sekai_saikyou_no_kouei_meikyuukoku_no_shinjin_tansakusha",
    "animethemeUrl": "https://animethemes.moe/anime/sekai_saikyou_no_kouei_meikyuukoku_no_shinjin_tansakusha"
  },
  {
    "title": "license",
    "titleCN": "license",
    "anime": "Sekai Saikyou no Kouei: Meikyuukoku no Shinjin Tansakusha",
    "animeCN": "世界最强的后卫：迷宫国的新人探索者",
    "artist": "Redhair Rosy",
    "type": "OP",
    "popularity": 26830,
    "averageScore": 55,
    "anilistId": 198409,
    "slug": "sekai_saikyou_no_kouei_meikyuukoku_no_shinjin_tansakusha",
    "animethemeUrl": "https://animethemes.moe/anime/sekai_saikyou_no_kouei_meikyuukoku_no_shinjin_tansakusha"
  },
  {
    "title": "Romantic ga Hoshii nara feat. Nao Kosaka, Youko Shougenji, Kaho Fujishima (Hinatazaka46)",
    "titleCN": "Romantic ga Hoshii nara feat. Nao Kosaka, Youko Shougenji, Kaho Fujishima (Hinatazaka46)",
    "anime": "Nige Jouzu no Wakagimi 2nd Season",
    "animeCN": "擅逃的少主 第二季",
    "artist": "Botchi Boromaru, Nao Kosaka, Youko Shougenji, Kaho Fujishima",
    "type": "ED",
    "popularity": 26069,
    "averageScore": 76,
    "anilistId": 182616,
    "slug": "nige_jouzu_no_wakagimi_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/nige_jouzu_no_wakagimi_2nd_season"
  },
  {
    "title": "Onigoto",
    "titleCN": "Onigoto",
    "anime": "Nige Jouzu no Wakagimi 2nd Season",
    "animeCN": "擅逃的少主 第二季",
    "artist": "Kento Nakajima",
    "type": "OP",
    "popularity": 26069,
    "averageScore": 76,
    "anilistId": 182616,
    "slug": "nige_jouzu_no_wakagimi_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/nige_jouzu_no_wakagimi_2nd_season"
  },
  {
    "title": "Suteki na Kanchigai",
    "titleCN": "Suteki na Kanchigai",
    "anime": "Saikyou Degarashi Ouji no Anyaku Teii Arasoi: Munou wo Enjiru SS Rank Ouji wa Koui Keishou-sen wo Kage kara Shihai suru",
    "animeCN": "最强人渣王子的暗黑帝位之争",
    "artist": "ClaWn",
    "type": "ED",
    "popularity": 24137,
    "averageScore": 58,
    "anilistId": 169582,
    "slug": "saikyou_degarashi_ouji_no_anyaku_teii_arasoi_munou_wo_enjiru_ss_rank_ouji_wa_koui_keishousen_wo_kage_kara_shihai_suru",
    "animethemeUrl": "https://animethemes.moe/anime/saikyou_degarashi_ouji_no_anyaku_teii_arasoi_munou_wo_enjiru_ss_rank_ouji_wa_koui_keishousen_wo_kage_kara_shihai_suru"
  },
  {
    "title": "Script",
    "titleCN": "Script",
    "anime": "Saikyou Degarashi Ouji no Anyaku Teii Arasoi: Munou wo Enjiru SS Rank Ouji wa Koui Keishou-sen wo Kage kara Shihai suru",
    "animeCN": "最强人渣王子的暗黑帝位之争",
    "artist": "BUDDiiS",
    "type": "OP",
    "popularity": 24137,
    "averageScore": 58,
    "anilistId": 169582,
    "slug": "saikyou_degarashi_ouji_no_anyaku_teii_arasoi_munou_wo_enjiru_ss_rank_ouji_wa_koui_keishousen_wo_kage_kara_shihai_suru",
    "animethemeUrl": "https://animethemes.moe/anime/saikyou_degarashi_ouji_no_anyaku_teii_arasoi_munou_wo_enjiru_ss_rank_ouji_wa_koui_keishousen_wo_kage_kara_shihai_suru"
  },
  {
    "title": "Very Good Encount",
    "titleCN": "Very Good Encount",
    "anime": "Hanaori-san wa Tensei Shite mo Kenka ga Shitai",
    "animeCN": "花织小姐转生也想打架",
    "artist": "Maaya Uchida",
    "type": "ED",
    "popularity": 23253,
    "averageScore": 69,
    "anilistId": 199066,
    "slug": "hanaorisan_wa_tensei_shite_mo_kenka_ga_shitai",
    "animethemeUrl": "https://animethemes.moe/anime/hanaorisan_wa_tensei_shite_mo_kenka_ga_shitai"
  },
  {
    "title": "High Maintenance Girl",
    "titleCN": "High Maintenance Girl",
    "anime": "Hanaori-san wa Tensei Shite mo Kenka ga Shitai",
    "animeCN": "花织小姐转生也想打架",
    "artist": "Masayoshi Ooishi",
    "type": "OP",
    "popularity": 23253,
    "averageScore": 69,
    "anilistId": 199066,
    "slug": "hanaorisan_wa_tensei_shite_mo_kenka_ga_shitai",
    "animethemeUrl": "https://animethemes.moe/anime/hanaorisan_wa_tensei_shite_mo_kenka_ga_shitai"
  },
  {
    "title": "Goodbye Lullaby",
    "titleCN": "Goodbye Lullaby",
    "anime": "Buchigire Reijou wa Houfuku wo Chikaimashita.: Madousho no Chikara de Sokoku wo Tataki Tsubushimasu",
    "animeCN": "暴怒大小姐发誓复仇：以魔导书之力击溃祖国",
    "artist": "Aguri Oonishi",
    "type": "ED",
    "popularity": 22652,
    "averageScore": 67,
    "anilistId": 199408,
    "slug": "buchigire_reijou_wa_houfuku_wo_chikaimashita_madousho_no_chikara_de_sokoku_wo_tataki_tsubushimasu",
    "animethemeUrl": "https://animethemes.moe/anime/buchigire_reijou_wa_houfuku_wo_chikaimashita_madousho_no_chikara_de_sokoku_wo_tataki_tsubushimasu"
  },
  {
    "title": "Q.E.D.",
    "titleCN": "Q.E.D.",
    "anime": "Buchigire Reijou wa Houfuku wo Chikaimashita.: Madousho no Chikara de Sokoku wo Tataki Tsubushimasu",
    "animeCN": "暴怒大小姐发誓复仇：以魔导书之力击溃祖国",
    "artist": "Yui Ogura",
    "type": "OP",
    "popularity": 22652,
    "averageScore": 67,
    "anilistId": 199408,
    "slug": "buchigire_reijou_wa_houfuku_wo_chikaimashita_madousho_no_chikara_de_sokoku_wo_tataki_tsubushimasu",
    "animethemeUrl": "https://animethemes.moe/anime/buchigire_reijou_wa_houfuku_wo_chikaimashita_madousho_no_chikara_de_sokoku_wo_tataki_tsubushimasu"
  },
  {
    "title": "Shinboshi",
    "titleCN": "Shinboshi",
    "anime": "Oni no Hanayome",
    "animeCN": "鬼之新娘",
    "artist": "Ikusaburo Yamazaki",
    "type": "ED",
    "popularity": 20700,
    "averageScore": 68,
    "anilistId": 194219,
    "slug": "oni_no_hanayome",
    "animethemeUrl": "https://animethemes.moe/anime/oni_no_hanayome"
  },
  {
    "title": "Hitokoto",
    "titleCN": "Hitokoto",
    "anime": "Oni no Hanayome",
    "animeCN": "鬼之新娘",
    "artist": "ClariS",
    "type": "OP",
    "popularity": 20700,
    "averageScore": 68,
    "anilistId": 194219,
    "slug": "oni_no_hanayome",
    "animethemeUrl": "https://animethemes.moe/anime/oni_no_hanayome"
  },
  {
    "title": "Unknown Me",
    "titleCN": "Unknown Me",
    "anime": "Mujikaku Seijo wa Kyou mo Muishiki ni Chikara wo Tare Nagasu",
    "animeCN": "无自觉圣女今天也无意识释放力量",
    "artist": "Utahime Dream All Stars",
    "type": "ED",
    "popularity": 19684,
    "averageScore": 63,
    "anilistId": 196219,
    "slug": "mujikaku_seijo_wa_kyou_mo_muishiki_ni_chikara_wo_tare_nagasu",
    "animethemeUrl": "https://animethemes.moe/anime/mujikaku_seijo_wa_kyou_mo_muishiki_ni_chikara_wo_tare_nagasu"
  },
  {
    "title": "Windmaker",
    "titleCN": "Windmaker",
    "anime": "Mujikaku Seijo wa Kyou mo Muishiki ni Chikara wo Tare Nagasu",
    "animeCN": "无自觉圣女今天也无意识释放力量",
    "artist": "Kaya",
    "type": "OP",
    "popularity": 19684,
    "averageScore": 63,
    "anilistId": 196219,
    "slug": "mujikaku_seijo_wa_kyou_mo_muishiki_ni_chikara_wo_tare_nagasu",
    "animethemeUrl": "https://animethemes.moe/anime/mujikaku_seijo_wa_kyou_mo_muishiki_ni_chikara_wo_tare_nagasu"
  },
  {
    "title": "En no Tsuki",
    "titleCN": "En no Tsuki",
    "anime": "Tefuda ga Oome no Victoria",
    "animeCN": "手牌过多的维多利亚",
    "artist": "KI_EN",
    "type": "ED",
    "popularity": 15041,
    "averageScore": 73,
    "anilistId": 198709,
    "slug": "tefuda_ga_oome_no_victoria",
    "animethemeUrl": "https://animethemes.moe/anime/tefuda_ga_oome_no_victoria"
  },
  {
    "title": "Isshin",
    "titleCN": "Isshin",
    "anime": "Tefuda ga Oome no Victoria",
    "animeCN": "手牌过多的维多利亚",
    "artist": "Haku.",
    "type": "OP",
    "popularity": 15041,
    "averageScore": 73,
    "anilistId": 198709,
    "slug": "tefuda_ga_oome_no_victoria",
    "animethemeUrl": "https://animethemes.moe/anime/tefuda_ga_oome_no_victoria"
  },
  {
    "title": "Holy Sweet Home",
    "titleCN": "Holy Sweet Home",
    "anime": "Suterare Seijo no Isekai Gohantabi: Kakure Skill de Camping Car wo Shoukan Shimashita",
    "animeCN": "被抛弃圣女异世界饭旅：以隐藏技能召唤房车",
    "artist": "Onkan Lemonade",
    "type": "ED",
    "popularity": 13873,
    "averageScore": 61,
    "anilistId": 209504,
    "slug": "suterare_seijo_no_isekai_gohantabi_kakure_skill_de_camping_car_wo_shoukan_shimashita",
    "animethemeUrl": "https://animethemes.moe/anime/suterare_seijo_no_isekai_gohantabi_kakure_skill_de_camping_car_wo_shoukan_shimashita"
  },
  {
    "title": "Butterfly",
    "titleCN": "Butterfly",
    "anime": "Suterare Seijo no Isekai Gohantabi: Kakure Skill de Camping Car wo Shoukan Shimashita",
    "animeCN": "被抛弃圣女异世界饭旅：以隐藏技能召唤房车",
    "artist": "INUWASI",
    "type": "OP",
    "popularity": 13873,
    "averageScore": 61,
    "anilistId": 209504,
    "slug": "suterare_seijo_no_isekai_gohantabi_kakure_skill_de_camping_car_wo_shoukan_shimashita",
    "animethemeUrl": "https://animethemes.moe/anime/suterare_seijo_no_isekai_gohantabi_kakure_skill_de_camping_car_wo_shoukan_shimashita"
  },
  {
    "title": "Hinatabokko",
    "titleCN": "Hinatabokko",
    "anime": "Reiwa no Dara-san",
    "animeCN": "令和的懒懒小姐",
    "artist": "REIRIE",
    "type": "ED",
    "popularity": 13311,
    "averageScore": 65,
    "anilistId": 203880,
    "slug": "reiwa_no_darasan",
    "animethemeUrl": "https://animethemes.moe/anime/reiwa_no_darasan"
  },
  {
    "title": "Dara Dara ♡ Dancing",
    "titleCN": "Dara Dara ♡ Dancing",
    "anime": "Reiwa no Dara-san",
    "animeCN": "令和的懒懒小姐",
    "artist": "Minami Tsuda, Mutsumi Tamura, Momoka Terasawa, Masaki Terasoma",
    "type": "OP",
    "popularity": 13311,
    "averageScore": 65,
    "anilistId": 203880,
    "slug": "reiwa_no_darasan",
    "animethemeUrl": "https://animethemes.moe/anime/reiwa_no_darasan"
  },
  {
    "title": "Clair",
    "titleCN": "Clair",
    "anime": "Ibitte Konai Gibo to Gishi",
    "animeCN": "不扭曲的继母与义子",
    "artist": "AVAM",
    "type": "ED",
    "popularity": 11718,
    "averageScore": 64,
    "anilistId": 196356,
    "slug": "ibitte_konai_gibo_to_gishi",
    "animethemeUrl": "https://animethemes.moe/anime/ibitte_konai_gibo_to_gishi"
  },
  {
    "title": "Amayadori no Shoukei",
    "titleCN": "Amayadori no Shoukei",
    "anime": "Ibitte Konai Gibo to Gishi",
    "animeCN": "不扭曲的继母与义子",
    "artist": "Lia",
    "type": "OP",
    "popularity": 11718,
    "averageScore": 64,
    "anilistId": 196356,
    "slug": "ibitte_konai_gibo_to_gishi",
    "animethemeUrl": "https://animethemes.moe/anime/ibitte_konai_gibo_to_gishi"
  },
  {
    "title": "Saishuukai",
    "titleCN": "Saishuukai",
    "anime": "\"Kimi wo Aisuru Ki wa nai\" to Itta Jiki Koushaku-sama ga Naze ka Dekiai Shitekimasu",
    "animeCN": "「我没有爱你的打算」的时之公爵大人为何溺爱我",
    "artist": "sorato",
    "type": "ED",
    "popularity": 11664,
    "averageScore": 65,
    "anilistId": 208225,
    "slug": "kimi_wo_aisuru_ki_wa_nai_to_itta_jiki_koushakusama_ga_naze_ka_dekiai_shitekimasu",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_wo_aisuru_ki_wa_nai_to_itta_jiki_koushakusama_ga_naze_ka_dekiai_shitekimasu"
  },
  {
    "title": "Itsuka Chanto.",
    "titleCN": "Itsuka Chanto.",
    "anime": "\"Kimi wo Aisuru Ki wa nai\" to Itta Jiki Koushaku-sama ga Naze ka Dekiai Shitekimasu",
    "animeCN": "「我没有爱你的打算」的时之公爵大人为何溺爱我",
    "artist": "Riria.",
    "type": "OP",
    "popularity": 11664,
    "averageScore": 65,
    "anilistId": 208225,
    "slug": "kimi_wo_aisuru_ki_wa_nai_to_itta_jiki_koushakusama_ga_naze_ka_dekiai_shitekimasu",
    "animethemeUrl": "https://animethemes.moe/anime/kimi_wo_aisuru_ki_wa_nai_to_itta_jiki_koushakusama_ga_naze_ka_dekiai_shitekimasu"
  },
  {
    "title": "Conifer",
    "titleCN": "Conifer",
    "anime": "Kore Kaite Shine",
    "animeCN": "写了这个去死",
    "artist": "Regal Lily",
    "type": "ED",
    "popularity": 10634,
    "averageScore": 77,
    "anilistId": 188525,
    "slug": "kore_kaite_shine",
    "animethemeUrl": "https://animethemes.moe/anime/kore_kaite_shine"
  },
  {
    "title": "Isho",
    "titleCN": "Isho",
    "anime": "Kore Kaite Shine",
    "animeCN": "写了这个去死",
    "artist": "Tatsuya Kitani",
    "type": "OP",
    "popularity": 10634,
    "averageScore": 77,
    "anilistId": 188525,
    "slug": "kore_kaite_shine",
    "animethemeUrl": "https://animethemes.moe/anime/kore_kaite_shine"
  },
  {
    "title": "Reunion",
    "titleCN": "Reunion",
    "anime": "Sora wa Akai Kawa no Hotori",
    "animeCN": "天空在红河之畔",
    "artist": "Miisha Shimizu",
    "type": "ED",
    "popularity": 10350,
    "averageScore": 61,
    "anilistId": 207809,
    "slug": "sora_wa_akai_kawa_no_hotori",
    "animethemeUrl": "https://animethemes.moe/anime/sora_wa_akai_kawa_no_hotori"
  },
  {
    "title": "Akatsuki no Sora",
    "titleCN": "Akatsuki no Sora",
    "anime": "Sora wa Akai Kawa no Hotori",
    "animeCN": "天空在红河之畔",
    "artist": "Hiroki Nanami",
    "type": "OP",
    "popularity": 10350,
    "averageScore": 61,
    "anilistId": 207809,
    "slug": "sora_wa_akai_kawa_no_hotori",
    "animethemeUrl": "https://animethemes.moe/anime/sora_wa_akai_kawa_no_hotori"
  }
];
