// 曲库候选（精简版：每季度人气 top 8 部番剧，每部 OP1+ED1）
// 由 scripts/fetch-season.mjs 生成，人工复核后可合并进 songs.js
export const CANDIDATES = [
  {
    "title": "Inori, Owareba",
    "titleCN": "Inori, Owareba",
    "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
    "animeCN": "无职转生Ⅲ ～异世界认真活下去～",
    "artist": "Mika Nakashima",
    "type": "ED",
    "popularity": 151620,
    "averageScore": 84,
    "anilistId": 178789,
    "slug": "mushoku_tensei_iii_isekai_ittara_honki_dasu",
    "animethemeUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu"
  },
  {
    "title": "Ketsui no Uta",
    "titleCN": "Ketsui no Uta",
    "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
    "animeCN": "无职转生Ⅲ ～异世界认真活下去～",
    "artist": "Yuiko Oohara",
    "type": "OP",
    "popularity": 151620,
    "averageScore": 84,
    "anilistId": 178789,
    "slug": "mushoku_tensei_iii_isekai_ittara_honki_dasu",
    "animethemeUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu"
  },
  {
    "title": "Fiction",
    "titleCN": "Fiction",
    "anime": "Super no Ura de Yani Suu Futari",
    "animeCN": "在超市后门吸烟的二人",
    "artist": "imase",
    "type": "ED",
    "popularity": 115213,
    "averageScore": 82,
    "anilistId": 196187,
    "slug": "super_no_ura_de_yani_suu_futari",
    "animethemeUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari"
  },
  {
    "title": "Ichijiku Kemuri",
    "titleCN": "Ichijiku Kemuri",
    "anime": "Super no Ura de Yani Suu Futari",
    "animeCN": "在超市后门吸烟的二人",
    "artist": "Zutto Mayonaka de Ii no ni.",
    "type": "OP",
    "popularity": 115213,
    "averageScore": 82,
    "anilistId": 196187,
    "slug": "super_no_ura_de_yani_suu_futari",
    "animethemeUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari"
  },
  {
    "title": "Weiter! Weiter!",
    "titleCN": "Weiter! Weiter!",
    "anime": "Youjo Senki II",
    "animeCN": "幼女战记Ⅱ",
    "artist": "Aoi Yuuki",
    "type": "ED",
    "popularity": 90759,
    "averageScore": 80,
    "anilistId": 135865,
    "slug": "youjo_senki_ii",
    "animethemeUrl": "https://animethemes.moe/anime/youjo_senki_ii"
  },
  {
    "title": "Why? RED induction",
    "titleCN": "Why? RED induction",
    "anime": "Youjo Senki II",
    "animeCN": "幼女战记Ⅱ",
    "artist": "MYTH & ROID",
    "type": "OP",
    "popularity": 90759,
    "averageScore": 80,
    "anilistId": 135865,
    "slug": "youjo_senki_ii",
    "animethemeUrl": "https://animethemes.moe/anime/youjo_senki_ii"
  },
  {
    "title": "Rasen",
    "titleCN": "Rasen",
    "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
    "animeCN": "死神 千年血战篇-相克谭-",
    "artist": "9Lana",
    "type": "ED",
    "popularity": 82571,
    "averageScore": 90,
    "anilistId": 185874,
    "slug": "bleach_sennen_kessenhen_kashintan",
    "animethemeUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan"
  },
  {
    "title": "I-BULL",
    "titleCN": "I-BULL",
    "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
    "animeCN": "死神 千年血战篇-相克谭-",
    "artist": "jo0ji",
    "type": "OP",
    "popularity": 82571,
    "averageScore": 90,
    "anilistId": 185874,
    "slug": "bleach_sennen_kessenhen_kashintan",
    "animethemeUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan"
  },
  {
    "title": "Kemuri to Blue",
    "titleCN": "Kemuri to Blue",
    "anime": "Yani Neko",
    "animeCN": "夜猫",
    "artist": "Necry Talkie",
    "type": "ED",
    "popularity": 70498,
    "averageScore": 67,
    "anilistId": 207141,
    "slug": "yani_neko",
    "animethemeUrl": "https://animethemes.moe/anime/yani_neko"
  },
  {
    "title": "Nanmonee",
    "titleCN": "Nanmonee",
    "anime": "Yani Neko",
    "animeCN": "夜猫",
    "artist": "Wasureranneyo",
    "type": "OP",
    "popularity": 70498,
    "averageScore": 67,
    "anilistId": 207141,
    "slug": "yani_neko",
    "animethemeUrl": "https://animethemes.moe/anime/yani_neko"
  },
  {
    "title": "Groooovy",
    "titleCN": "Groooovy",
    "anime": "BLACK TORCH",
    "animeCN": "黑之火炬",
    "artist": "I Don't Like Mondays.",
    "type": "ED",
    "popularity": 65187,
    "averageScore": 70,
    "anilistId": 187538,
    "slug": "black_torch",
    "animethemeUrl": "https://animethemes.moe/anime/black_torch"
  },
  {
    "title": "FREEZE ME UP",
    "titleCN": "FREEZE ME UP",
    "anime": "BLACK TORCH",
    "animeCN": "黑之火炬",
    "artist": "SiM",
    "type": "OP",
    "popularity": 65187,
    "averageScore": 70,
    "anilistId": 187538,
    "slug": "black_torch",
    "animethemeUrl": "https://animethemes.moe/anime/black_torch"
  },
  {
    "title": "Lv.1 Shokugyou:Ningen",
    "titleCN": "Lv.1 Shokugyou:Ningen",
    "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
    "animeCN": "被放逐的转生重骑士靠游戏知识无双",
    "artist": "ReoNa",
    "type": "ED",
    "popularity": 58925,
    "averageScore": 66,
    "anilistId": 180136,
    "slug": "tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
    "animethemeUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru"
  },
  {
    "title": "Awake",
    "titleCN": "Awake",
    "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
    "animeCN": "被放逐的转生重骑士靠游戏知识无双",
    "artist": "SPYAIR",
    "type": "OP",
    "popularity": 58925,
    "averageScore": 66,
    "anilistId": 180136,
    "slug": "tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
    "animethemeUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru"
  },
  {
    "title": "Unmei no Kimi",
    "titleCN": "Unmei no Kimi",
    "anime": "Seihantai na Kimi to Boku 2nd Season",
    "animeCN": "反方向的你和我 第二季",
    "artist": "Mega Shinnosuke",
    "type": "ED",
    "popularity": 57033,
    "averageScore": 82,
    "anilistId": 210031,
    "slug": "seihantai_na_kimi_to_boku_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season"
  },
  {
    "title": "Nekojarashi",
    "titleCN": "Nekojarashi",
    "anime": "Seihantai na Kimi to Boku 2nd Season",
    "animeCN": "反方向的你和我 第二季",
    "artist": "7co",
    "type": "OP",
    "popularity": 57033,
    "averageScore": 82,
    "anilistId": 210031,
    "slug": "seihantai_na_kimi_to_boku_2nd_season",
    "animethemeUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season"
  }
];
