// Reviewed seasonal pools. Keep SONGS in songs.js unchanged.
// Source: AniList popularity + AnimeThemes OP1/ED1; season is the January/April/July/October start month.
export const SEASONAL_POOLS = {
  "2026-04": [
    {
      "titleCN": "Recollect",
      "title": "Recollect",
      "anime": "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season",
      "artist": "Konomi Suzuki, Ashnikko",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 189046,
      "animeNative": "Re:ゼロから始める異世界生活 4th season",
      "animethemesUrl": "https://animethemes.moe/anime/rezero_kara_hajimeru_isekai_seikatsu_4th_season",
      "youtubeVideoId": "6yOpDa4GsNg",
      "animeCN": "Re：从零开始的异世界生活 第四季"
    },
    {
      "titleCN": "Ender Ember",
      "title": "Ender Ember",
      "anime": "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season",
      "artist": "MYTH & ROID, TK from Ling tosite sigure",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 189046,
      "animeNative": "Re:ゼロから始める異世界生活 4th season",
      "animethemesUrl": "https://animethemes.moe/anime/rezero_kara_hajimeru_isekai_seikatsu_4th_season",
      "animeCN": "Re：从零开始的异世界生活 第四季"
    },
    {
      "titleCN": "Esoragoto",
      "title": "Esoragoto",
      "anime": "Tensei shitara Slime Datta Ken 4th Season",
      "artist": "Eir Aoi",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 182205,
      "animeNative": "転生したらスライムだった件 第4期 第1&2クール",
      "animethemesUrl": "https://animethemes.moe/anime/tensei_shitara_slime_datta_ken_4th_season",
      "youtubeVideoId": "ILfcwl8ZKDs",
      "animeCN": "关于我转生变成史莱姆这档事 第四季"
    },
    {
      "titleCN": "Katsubou",
      "title": "Katsubou",
      "anime": "Tensei shitara Slime Datta Ken 4th Season",
      "artist": "CiON",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 182205,
      "animeNative": "転生したらスライムだった件 第4期 第1&2クール",
      "animethemesUrl": "https://animethemes.moe/anime/tensei_shitara_slime_datta_ken_4th_season",
      "animeCN": "关于我转生变成史莱姆这档事 第四季"
    },
    {
      "titleCN": "Tobu Toki",
      "title": "Tobu Toki",
      "anime": "Yomi no Tsugai",
      "artist": "Vaundy",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 195600,
      "animeNative": "黄泉のツガイ",
      "animethemesUrl": "https://animethemes.moe/anime/yomi_no_tsugai",
      "youtubeVideoId": "ARj1adoUoEU",
      "animeCN": "黄泉使者"
    },
    {
      "titleCN": "Tobou yo",
      "title": "Tobou yo",
      "anime": "Yomi no Tsugai",
      "artist": "yama",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 195600,
      "animeNative": "黄泉のツガイ",
      "animethemesUrl": "https://animethemes.moe/anime/yomi_no_tsugai",
      "animeCN": "黄泉使者"
    },
    {
      "titleCN": "BELIEVERS",
      "title": "BELIEVERS",
      "anime": "Tsue to Tsurugi no Wistoria Season 2",
      "artist": "ASH DA HERO",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 182300,
      "animeNative": "杖と剣のウィストリア Season2",
      "animethemesUrl": "https://animethemes.moe/anime/tsue_to_tsurugi_no_wistoria_season_2",
      "animeCN": "杖与剑的魔剑谭 第二季"
    },
    {
      "titleCN": "Reachlight",
      "title": "Reachlight",
      "anime": "Tsue to Tsurugi no Wistoria Season 2",
      "artist": "Shiyui",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 182300,
      "animeNative": "杖と剣のウィストリア Season2",
      "animethemesUrl": "https://animethemes.moe/anime/tsue_to_tsurugi_no_wistoria_season_2",
      "youtubeVideoId": "Pn0c9QIiqbo",
      "animeCN": "杖与剑的魔剑谭 第二季"
    },
    {
      "titleCN": "MONSTER",
      "title": "MONSTER",
      "anime": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season 2-nensei-hen Ichi Gakki",
      "artist": "Eir Aoi",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 180745,
      "animeNative": "ようこそ実力至上主義の教室へ 4th Season 2年生編1学期",
      "animethemesUrl": "https://animethemes.moe/anime/youkoso_jitsuryoku_shijou_shugi_no_kyoushitsu_e_4th_season_2nenseihen_ichi_gakki",
      "animeCN": "欢迎来到实力至上主义的教室 第四季"
    },
    {
      "titleCN": "Liar Veil",
      "title": "Liar Veil",
      "anime": "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 4th Season 2-nensei-hen Ichi Gakki",
      "artist": "ZAQ",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 180745,
      "animeNative": "ようこそ実力至上主義の教室へ 4th Season 2年生編1学期",
      "animethemesUrl": "https://animethemes.moe/anime/youkoso_jitsuryoku_shijou_shugi_no_kyoushitsu_e_4th_season_2nenseihen_ichi_gakki",
      "youtubeVideoId": "jl7GmJBNxk4",
      "animeCN": "欢迎来到实力至上主义的教室 第四季"
    },
    {
      "titleCN": "Submarine Youth",
      "title": "Submarine Youth",
      "anime": "Class de 2-banme ni Kawaii Onnanoko to Tomodachi ni Natta",
      "artist": "reGretGirl",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 169580,
      "animeNative": "クラスで２番目に可愛い女の子と友だちになった",
      "animethemesUrl": "https://animethemes.moe/anime/class_de_2banme_ni_kawaii_onnanoko_to_tomodachi_ni_natta",
      "animeCN": "和班上第二可爱的女孩成为朋友"
    },
    {
      "titleCN": "Zutto 1-ban ni Shite ne",
      "title": "Zutto 1-ban ni Shite ne",
      "anime": "Class de 2-banme ni Kawaii Onnanoko to Tomodachi ni Natta",
      "artist": "Koresawa",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 169580,
      "animeNative": "クラスで２番目に可愛い女の子と友だちになった",
      "animethemesUrl": "https://animethemes.moe/anime/class_de_2banme_ni_kawaii_onnanoko_to_tomodachi_ni_natta",
      "animeCN": "和班上第二可爱的女孩成为朋友"
    },
    {
      "titleCN": "Kill or Kiss",
      "title": "Kill or Kiss",
      "anime": "MARRIAGETOXIN",
      "artist": "Yurina Hirate",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 199547,
      "animeNative": "マリッジトキシン",
      "animethemesUrl": "https://animethemes.moe/anime/marriagetoxin",
      "youtubeVideoId": "M2wVo7qaeVA",
      "animeCN": "婚姻剧毒"
    },
    {
      "titleCN": "Shake Na Baby",
      "title": "Shake Na Baby",
      "anime": "MARRIAGETOXIN",
      "artist": "AKASAKI",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 199547,
      "animeNative": "マリッジトキシン",
      "animethemesUrl": "https://animethemes.moe/anime/marriagetoxin",
      "animeCN": "婚姻剧毒"
    },
    {
      "titleCN": "Skins",
      "title": "Skins",
      "anime": "Dr. STONE: SCIENCE FUTURE Part 3",
      "artist": "Asian Kung-Fu Generation",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 199221,
      "animeNative": "Dr.STONE SCIENCE FUTURE 3クール",
      "animethemesUrl": "https://animethemes.moe/anime/dr_stone_science_future_part_3",
      "animeCN": "石纪元 科学与未来 第3部分"
    },
    {
      "titleCN": "ROCKET",
      "title": "ROCKET",
      "anime": "Dr. STONE: SCIENCE FUTURE Part 3",
      "artist": "BURNOUT SYNDROMES",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 199221,
      "animeNative": "Dr.STONE SCIENCE FUTURE 3クール",
      "animethemesUrl": "https://animethemes.moe/anime/dr_stone_science_future_part_3",
      "animeCN": "石纪元 科学与未来 第3部分"
    },
    {
      "titleCN": "Toumei",
      "title": "Toumei",
      "anime": "Koori no Jouheki",
      "artist": "Novelbright",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 186497,
      "animeNative": "氷の城壁",
      "animethemesUrl": "https://animethemes.moe/anime/koori_no_jouheki",
      "animeCN": "冰之城墙"
    },
    {
      "titleCN": "Sakasama",
      "title": "Sakasama",
      "anime": "Koori no Jouheki",
      "artist": "Polkadot Stingray",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 186497,
      "animeNative": "氷の城壁",
      "animethemesUrl": "https://animethemes.moe/anime/koori_no_jouheki",
      "animeCN": "冰之城墙"
    },
    {
      "titleCN": "Kimi wa Koibito",
      "title": "Kimi wa Koibito",
      "anime": "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken 2nd Season",
      "artist": "Masayoshi Ooishi",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 170019,
      "animeNative": "お隣の天使様にいつの間にか駄目人間にされていた件 第2期",
      "animethemesUrl": "https://animethemes.moe/anime/otonari_no_tenshisama_ni_itsunomanika_dame_ningen_ni_sareteita_ken_2nd_season",
      "animeCN": "关于邻家的天使大人不知不觉把我惯成了废人这档子事 第二季"
    },
    {
      "titleCN": "Ureshii! Tanoshii! Daisuki!",
      "title": "Ureshii! Tanoshii! Daisuki!",
      "anime": "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken 2nd Season",
      "artist": "Manaka Iwami",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 170019,
      "animeNative": "お隣の天使様にいつの間にか駄目人間にされていた件 第2期",
      "animethemesUrl": "https://animethemes.moe/anime/otonari_no_tenshisama_ni_itsunomanika_dame_ningen_ni_sareteita_ken_2nd_season",
      "youtubeVideoId": "sZRWkXpekDE",
      "animeCN": "关于邻家的天使大人不知不觉把我惯成了废人这档子事 第二季"
    },
    {
      "titleCN": "HIDE AND SEEK",
      "title": "HIDE AND SEEK",
      "anime": "Otaku ni Yasashii Gal wa Inai!?",
      "artist": "i-dle",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 199588,
      "animeCN": "没有辣妹会对阿宅温柔!?",
      "animeNative": "オタクに優しいギャルはいない!?",
      "animethemesUrl": "https://animethemes.moe/anime/otaku_ni_yasashii_gal_wa_inai"
    },
    {
      "titleCN": "Isshou Nakako",
      "title": "Isshou Nakako",
      "anime": "Otaku ni Yasashii Gal wa Inai!?",
      "artist": "sunsoogirl",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 199588,
      "animeCN": "没有辣妹会对阿宅温柔!?",
      "animeNative": "オタクに優しいギャルはいない!?",
      "animethemesUrl": "https://animethemes.moe/anime/otaku_ni_yasashii_gal_wa_inai"
    },
    {
      "titleCN": "Kimi no Sei de Aishiteru",
      "title": "Kimi no Sei de Aishiteru",
      "anime": "Aishiteru Game wo Owarasetai",
      "artist": "CHiCO, HoneyWorks",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 194393,
      "animeNative": "愛してるゲームを終わらせたい",
      "animethemesUrl": "https://animethemes.moe/anime/aishiteru_game_wo_owarasetai",
      "animeCN": "想结束这场“我爱你”的游戏"
    },
    {
      "titleCN": "Little World",
      "title": "Little World",
      "anime": "Aishiteru Game wo Owarasetai",
      "artist": "PompadollS",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 194393,
      "animeNative": "愛してるゲームを終わらせたい",
      "animethemesUrl": "https://animethemes.moe/anime/aishiteru_game_wo_owarasetai",
      "animeCN": "想结束这场“我爱你”的游戏"
    },
    {
      "titleCN": "BEAUTIFUL",
      "title": "BEAUTIFUL",
      "anime": "Hime Kishi wa Barbaroi no Yome",
      "artist": "Mayu Maeshima",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 182483,
      "animeNative": "姫騎士は蛮族の嫁",
      "animethemesUrl": "https://animethemes.moe/anime/hime_kishi_wa_barbaroi_no_yome",
      "animeCN": "女骑士成为蛮族新娘"
    },
    {
      "titleCN": "Shirubeki Koto",
      "title": "Shirubeki Koto",
      "anime": "Hime Kishi wa Barbaroi no Yome",
      "artist": "sajou no hana",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 182483,
      "animeNative": "姫騎士は蛮族の嫁",
      "animethemesUrl": "https://animethemes.moe/anime/hime_kishi_wa_barbaroi_no_yome",
      "animeCN": "女骑士成为蛮族新娘"
    },
    {
      "titleCN": "It's a beautiful story",
      "title": "It's a beautiful story",
      "anime": "Isekai Nonbiri Nouka 2",
      "artist": "Aya Suzaki, Shino Shimoji",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 197824,
      "animeNative": "異世界のんびり農家２",
      "animethemesUrl": "https://animethemes.moe/anime/isekai_nonbiri_nouka_2",
      "animeCN": "异世界悠闲农家 第二季"
    },
    {
      "titleCN": "Sunny Steps",
      "title": "Sunny Steps",
      "anime": "Isekai Nonbiri Nouka 2",
      "artist": "Yui Hizuki",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 197824,
      "animeNative": "異世界のんびり農家２",
      "animethemesUrl": "https://animethemes.moe/anime/isekai_nonbiri_nouka_2",
      "youtubeVideoId": "40K8d9oveiY",
      "animeCN": "异世界悠闲农家 第二季"
    },
    {
      "titleCN": "ATTITUDE",
      "title": "ATTITUDE",
      "anime": "Kill Ao",
      "artist": "aespa",
      "type": "OP",
      "season": "2026-04",
      "anilistId": 198113,
      "animeNative": "キルアオ",
      "animethemesUrl": "https://animethemes.moe/anime/kill_ao",
      "animeCN": "杀手青春"
    },
    {
      "titleCN": "KILL SHOT",
      "title": "KILL SHOT",
      "anime": "Kill Ao",
      "artist": "RIIZE",
      "type": "ED",
      "season": "2026-04",
      "anilistId": 198113,
      "animeNative": "キルアオ",
      "animethemesUrl": "https://animethemes.moe/anime/kill_ao",
      "animeCN": "杀手青春"
    }
  ],
  "2026-07": [
    {
      "titleCN": "Ketsui no Uta",
      "title": "Ketsui no Uta",
      "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
      "artist": "Yuiko Oohara",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 178789,
      "animeNative": "無職転生Ⅲ ～異世界行ったら本気だす～",
      "animethemesUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu",
      "animeCN": "无职转生 第三季 ～到了异世界就拿出真本事～"
    },
    {
      "titleCN": "Inori, Owareba",
      "title": "Inori, Owareba",
      "anime": "Mushoku Tensei III: Isekai Ittara Honki Dasu",
      "artist": "Mika Nakashima",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 178789,
      "animeNative": "無職転生Ⅲ ～異世界行ったら本気だす～",
      "animethemesUrl": "https://animethemes.moe/anime/mushoku_tensei_iii_isekai_ittara_honki_dasu",
      "animeCN": "无职转生 第三季 ～到了异世界就拿出真本事～"
    },
    {
      "titleCN": "Ichijiku Kemuri",
      "title": "Ichijiku Kemuri",
      "anime": "Super no Ura de Yani Suu Futari",
      "artist": "Zutto Mayonaka de Ii no ni.",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 196187,
      "animeNative": "スーパーの裏でヤニ吸うふたり",
      "animethemesUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari",
      "animeCN": "在超市后门吸烟的二人"
    },
    {
      "titleCN": "Fiction",
      "title": "Fiction",
      "anime": "Super no Ura de Yani Suu Futari",
      "artist": "imase",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 196187,
      "animeNative": "スーパーの裏でヤニ吸うふたり",
      "animethemesUrl": "https://animethemes.moe/anime/super_no_ura_de_yani_suu_futari",
      "animeCN": "在超市后门吸烟的二人"
    },
    {
      "titleCN": "Why? RED induction",
      "title": "Why? RED induction",
      "anime": "Youjo Senki II",
      "artist": "MYTH & ROID",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 135865,
      "animeNative": "幼女戦記Ⅱ",
      "animethemesUrl": "https://animethemes.moe/anime/youjo_senki_ii",
      "animeCN": "幼女战记 第二季"
    },
    {
      "titleCN": "Weiter! Weiter!",
      "title": "Weiter! Weiter!",
      "anime": "Youjo Senki II",
      "artist": "Aoi Yuuki",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 135865,
      "animeNative": "幼女戦記Ⅱ",
      "animethemesUrl": "https://animethemes.moe/anime/youjo_senki_ii",
      "animeCN": "幼女战记 第二季"
    },
    {
      "titleCN": "I-BULL",
      "title": "I-BULL",
      "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
      "artist": "jo0ji",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 185874,
      "animeNative": "BLEACH 千年血戦篇-禍進譚-",
      "animethemesUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan",
      "animeCN": "死神 千年血战篇－祸进谭－"
    },
    {
      "titleCN": "Rasen",
      "title": "Rasen",
      "anime": "BLEACH: Sennen Kessen-hen - Kashin-tan",
      "artist": "9Lana",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 185874,
      "animeNative": "BLEACH 千年血戦篇-禍進譚-",
      "animethemesUrl": "https://animethemes.moe/anime/bleach_sennen_kessenhen_kashintan",
      "animeCN": "死神 千年血战篇－祸进谭－"
    },
    {
      "titleCN": "Nanmonee",
      "title": "Nanmonee",
      "anime": "Yani Neko",
      "artist": "Wasureranneyo",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 207141,
      "animeNative": "ヤニねこ",
      "animethemesUrl": "https://animethemes.moe/anime/yani_neko",
      "animeCN": "尼古喵喵"
    },
    {
      "titleCN": "Kemuri to Blue",
      "title": "Kemuri to Blue",
      "anime": "Yani Neko",
      "artist": "Necry Talkie",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 207141,
      "animeNative": "ヤニねこ",
      "animethemesUrl": "https://animethemes.moe/anime/yani_neko",
      "animeCN": "尼古喵喵"
    },
    {
      "titleCN": "FREEZE ME UP",
      "title": "FREEZE ME UP",
      "anime": "BLACK TORCH",
      "artist": "SiM",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 187538,
      "animeNative": "BLACK TORCH",
      "animethemesUrl": "https://animethemes.moe/anime/black_torch",
      "animeCN": "暗黑灯火"
    },
    {
      "titleCN": "Groooovy",
      "title": "Groooovy",
      "anime": "BLACK TORCH",
      "artist": "I Don't Like Mondays.",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 187538,
      "animeNative": "BLACK TORCH",
      "animethemesUrl": "https://animethemes.moe/anime/black_torch",
      "animeCN": "暗黑灯火"
    },
    {
      "titleCN": "Awake",
      "title": "Awake",
      "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
      "artist": "SPYAIR",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 180136,
      "animeNative": "追放された転生重騎士はゲーム知識で無双する",
      "animethemesUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
      "animeCN": "遭到流放的转生重骑士凭借游戏知识大开无双"
    },
    {
      "titleCN": "Lv.1 Shokugyou:Ningen",
      "title": "Lv.1 Shokugyou:Ningen",
      "anime": "Tsuihou Sareta Tensei Juukishi wa Game Chishiki de Musou Suru",
      "artist": "ReoNa",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 180136,
      "animeNative": "追放された転生重騎士はゲーム知識で無双する",
      "animethemesUrl": "https://animethemes.moe/anime/tsuihou_sareta_tensei_juukishi_wa_game_chishiki_de_musou_suru",
      "youtubeVideoId": "ylYL2rDyIHc",
      "animeCN": "遭到流放的转生重骑士凭借游戏知识大开无双"
    },
    {
      "titleCN": "Nekojarashi",
      "title": "Nekojarashi",
      "anime": "Seihantai na Kimi to Boku 2nd Season",
      "artist": "7co",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 210031,
      "animeNative": "正反対な君と僕 第2期",
      "animethemesUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season",
      "youtubeVideoId": "UFw27xYEvbY",
      "animeCN": "相反的你和我 第二季"
    },
    {
      "titleCN": "Unmei no Kimi",
      "title": "Unmei no Kimi",
      "anime": "Seihantai na Kimi to Boku 2nd Season",
      "artist": "Mega Shinnosuke",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 210031,
      "animeNative": "正反対な君と僕 第2期",
      "animethemesUrl": "https://animethemes.moe/anime/seihantai_na_kimi_to_boku_2nd_season",
      "animeCN": "相反的你和我 第二季"
    },
    {
      "titleCN": "Eureka Evrika",
      "title": "Eureka Evrika",
      "anime": "Nijusseiki Denki Mokuroku: Eureka Evrika",
      "artist": "Luna Goami",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 103303,
      "animeNative": "二十世紀電氣目録-ユーレカ・エヴリカ-",
      "animethemesUrl": "https://animethemes.moe/anime/nijusseiki_denki_mokuroku_eureka_evrika",
      "animeCN": "二十世纪电气目录"
    },
    {
      "titleCN": "Soarin'",
      "title": "Soarin'",
      "anime": "Nijusseiki Denki Mokuroku: Eureka Evrika",
      "artist": "Ginger Root",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 103303,
      "animeNative": "二十世紀電氣目録-ユーレカ・エヴリカ-",
      "animethemesUrl": "https://animethemes.moe/anime/nijusseiki_denki_mokuroku_eureka_evrika",
      "animeCN": "二十世纪电气目录"
    },
    {
      "titleCN": "Amore",
      "title": "Amore",
      "anime": "Kimi ga Shinu made Koi wo Shitai",
      "artist": "ReoNa",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 187260,
      "animeNative": "きみが死ぬまで恋をしたい",
      "animethemesUrl": "https://animethemes.moe/anime/kimi_ga_shinu_made_koi_wo_shitai",
      "animeCN": "与你相恋到生命尽头"
    },
    {
      "titleCN": "Eternal",
      "title": "Eternal",
      "anime": "Kimi ga Shinu made Koi wo Shitai",
      "artist": "sajou no hana",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 187260,
      "animeNative": "きみが死ぬまで恋をしたい",
      "animethemesUrl": "https://animethemes.moe/anime/kimi_ga_shinu_made_koi_wo_shitai",
      "animeCN": "与你相恋到生命尽头"
    },
    {
      "titleCN": "Jinsei End Roll",
      "title": "Jinsei End Roll",
      "anime": "Otomege Sekai wa Mob ni Kibishii Sekai desu 2",
      "artist": "Ando",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 159309,
      "animeNative": "乙女ゲー世界はモブに厳しい世界です2",
      "animethemesUrl": "https://animethemes.moe/anime/otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2",
      "animeCN": "恋爱游戏世界对路人角色很不友好 第二季"
    },
    {
      "titleCN": "Ashita wa Ashita no Ke Sera Sera!",
      "title": "Ashita wa Ashita no Ke Sera Sera!",
      "anime": "Otomege Sekai wa Mob ni Kibishii Sekai desu 2",
      "artist": "MEISHOHIKOKAI",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 159309,
      "animeNative": "乙女ゲー世界はモブに厳しい世界です2",
      "animethemesUrl": "https://animethemes.moe/anime/otomege_sekai_wa_mob_ni_kibishii_sekai_desu_2",
      "animeCN": "恋爱游戏世界对路人角色很不友好 第二季"
    },
    {
      "titleCN": "GO GHOST",
      "title": "GO GHOST",
      "anime": "Koukaku Kidoutai: THE GHOST IN THE SHELL",
      "artist": "King Gnu",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 177699,
      "animeNative": "攻殻機動隊 THE GHOST IN THE SHELL",
      "animethemesUrl": "https://animethemes.moe/anime/koukaku_kidoutai_the_ghost_in_the_shell",
      "animeCN": "攻壳机动队 THE GHOST IN THE SHELL"
    },
    {
      "titleCN": "Blue",
      "title": "Blue",
      "anime": "Koukaku Kidoutai: THE GHOST IN THE SHELL",
      "artist": "millennium parade",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 177699,
      "animeNative": "攻殻機動隊 THE GHOST IN THE SHELL",
      "animethemesUrl": "https://animethemes.moe/anime/koukaku_kidoutai_the_ghost_in_the_shell",
      "animeCN": "攻壳机动队 THE GHOST IN THE SHELL"
    },
    {
      "titleCN": "Roman Kaidou, Osanpo-chuu",
      "title": "Roman Kaidou, Osanpo-chuu",
      "anime": "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu II",
      "artist": "PelleK",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 185542,
      "animeNative": "骸骨騎士様、只今異世界へお出掛け中Ⅱ",
      "animethemesUrl": "https://animethemes.moe/anime/gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii",
      "animeCN": "骸骨骑士大人异世界冒险中 第二季"
    },
    {
      "titleCN": "Kiseki wa Okinai",
      "title": "Kiseki wa Okinai",
      "anime": "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu II",
      "artist": "DIALOGUE+",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 185542,
      "animeNative": "骸骨騎士様、只今異世界へお出掛け中Ⅱ",
      "animethemesUrl": "https://animethemes.moe/anime/gaikotsu_kishisama_tadaima_isekai_e_odekakechuu_ii",
      "animeCN": "骸骨骑士大人异世界冒险中 第二季"
    },
    {
      "titleCN": "Hitohira",
      "title": "Hitohira",
      "anime": "Toumei na Yoru ni Kakeru Kimi to, Me ni Mienai Koi wo Shita.",
      "artist": "Motohiro Hata",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 202269,
      "animeNative": "透明な夜に駆ける君と、目に見えない恋をした。",
      "animethemesUrl": "https://animethemes.moe/anime/toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita",
      "animeCN": "与奔驰于透明之夜的你，谈一场看不见的恋爱。"
    },
    {
      "titleCN": "Hikari",
      "title": "Hikari",
      "anime": "Toumei na Yoru ni Kakeru Kimi to, Me ni Mienai Koi wo Shita.",
      "artist": "Yui Sakurai",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 202269,
      "animeNative": "透明な夜に駆ける君と、目に見えない恋をした。",
      "animethemesUrl": "https://animethemes.moe/anime/toumei_na_yoru_ni_kakeru_kimi_to_me_ni_mienai_koi_wo_shita",
      "youtubeVideoId": "H_Ab3nKZUfM",
      "animeCN": "与奔驰于透明之夜的你，谈一场看不见的恋爱。"
    },
    {
      "titleCN": "Kurenai no Ha",
      "title": "Kurenai no Ha",
      "anime": "Katainaka no Ossan, Kensei ni Naru II",
      "artist": "Unicorn",
      "type": "OP",
      "season": "2026-07",
      "anilistId": 194829,
      "animeNative": "片田舎のおっさん、剣聖になるII",
      "animethemesUrl": "https://animethemes.moe/anime/katainaka_no_ossan_kensei_ni_naru_ii",
      "youtubeVideoId": "IpIYElR8MZY",
      "animeCN": "乡下大叔成为剑圣 第二季"
    },
    {
      "titleCN": "Mikansei",
      "title": "Mikansei",
      "anime": "Katainaka no Ossan, Kensei ni Naru II",
      "artist": "BLUE ENCOUNT",
      "type": "ED",
      "season": "2026-07",
      "anilistId": 194829,
      "animeNative": "片田舎のおっさん、剣聖になるII",
      "animethemesUrl": "https://animethemes.moe/anime/katainaka_no_ossan_kensei_ni_naru_ii",
      "animeCN": "乡下大叔成为剑圣 第二季"
    }
  ]
};
